const UPDATE_CHAT_MESSAGE_FIELD = 'app/modules/ui/chat/UPDATE_CHAT_MESSAGE_FIELD';
const CLEAR_CHAT_MESSAGE_FiELD = 'app/modules/ui/chat/CLEAR_CHAT_MESSAGE_FiELD';

export {
	UPDATE_CHAT_MESSAGE_FIELD,
	CLEAR_CHAT_MESSAGE_FiELD
};